shows:
  big_bang_theory:
    label: BBT
  bojeck_horesman:
    label: BoJack
  breaking_bad:
    label: BB
  dexter:
    label: Dexter
  game_of_thrones:
    label: GOT
  how_i_met_your_mother:
    label: HIMYM
  office:
    label: Office
  south_park:
    label: SP
