books:
  across_the_river_and_into_the_trees:
    label: AcrossRiver
    epub: "Ernest Hemingway - Across the River and Into the Trees.epub"
  adventures_of_huckleberry_finn:
    label: HuckFinn
    epub: "Mark Twain - Adventures of Huckleberry Finn.epub"
  animal_farm:
    label: AnimalFarm
    epub: "George Orwell - Animal Farm.epub"
  ballad_of_songbirds_and_snakes:
    label: BalladSong
    epub: "Suzanne Collins - The Ballad of Songbirds and Snakes.epub"
  bell_jar:
    label: BellJar
    epub: "Sylvia Plath - The Bell Jar.epub"
  beloved:
    label: Beloved
    epub: "Toni Morrison - Beloved.epub"
  blood_meridian:
    label: BloodMerid
    epub: "Cormac McCarthy - Blood Meridian.epub"
  boy_and_his_dog_at_the_end_of_the_world:
    label: BoyDogEnd
    epub: "C.A. Fletcher - A Boy and His Dog at the End of the World.epub"
  brave_new_world:
    label: BraveNew
    epub: "Aldous Huxley - Brave New World.epub"
  brief_wondrous_life_of_oscar_wao:
    label: OscarWao
    epub: "Junot Diaz - The Brief Wondrous Life of Oscar Wao.epub"
  catch_22:
    label: Catch22
    epub: "Joseph Heller - Catch-22.epub"
  catcher_in_the_rye:
    label: CatcherRye
    epub: "J.D. Salinger - The Catcher in the Rye.epub"
  chamber:
    label: Chamber
    epub: "John Grisham - The Chamber.epub"
  children_of_ruin:
    label: ChildRuin
    epub: "Adrian Tchaikovsky - Children of Ruin.epub"
  children_of_time:
    label: ChildTime
    epub: "Adrian Tchaikovsky - Children of Time.epub"
  color_purple:
    label: ColorPurple
    epub: "Alice Walker - The Color Purple.epub"
  confession:
    label: Confession
    epub: "John Grisham - The Confession.epub"
  corrections:
    label: Corrections
    epub: "Jonathan Franzen - The Corrections.epub"
  death_in_the_afternoon:
    label: DeathAftn
    epub: "Ernest Hemingway - Death in the Afternoon.epub"
  do_androids_dream_of_electric_sheep:
    label: DoAndroids
    epub: "Philip K. Dick - Do Androids Dream of Electric Sheep.epub"
  dune:
    label: Dune
    epub: "Frank Herbert - Dune.epub"
  east_of_eden:
    label: EastOfEden
    epub: "John Steinbeck - East of Eden.epub"
  fahrenheit_451:
    label: Fahr451
    epub: "Ray Bradbury - Fahrenheit 451.epub"
  fight_club:
    label: FightClub
    epub: "Chuck Palahniuk - Fight Club.epub"
  firm:
    label: Firm
    epub: "John Grisham - The Firm.epub"
  for_whom_the_bell_tolls:
    label: BellTolls
    epub: "Ernest Hemingway - For Whom the Bell Tolls.epub"
  foundation:
    label: Foundation
    epub: "Isaac Asimov - Foundation.epub"
  giver:
    label: Giver
    epub: "Lois Lowry - The Giver.epub"
  good_man_is_hard_to_find:
    label: GoodManHard
    epub: "Flannery O'Connor - A Good Man Is Hard to Find.epub"
  great_gatsby:
    label: Gatsby
    epub: "F. Scott Fitzgerald - The Great Gatsby.epub"
  green_hills_of_africa:
    label: GreenHills
    epub: "Ernest Hemingway - Green Hills of Africa.epub"
  harry_potter_01:
    label: HP1
    epub: "J.K. Rowling - Harry Potter 01 - Sorcerer's Stone.epub"
  harry_potter_02:
    label: HP2
    epub: "J.K. Rowling - Harry Potter 02 - Chamber of Secrets.epub"
  harry_potter_03:
    label: HP3
    epub: "J.K. Rowling - Harry Potter 03 - Prisoner of Azkaban.epub"
  harry_potter_04:
    label: HP4
    epub: "J.K. Rowling - Harry Potter 04 - Goblet of Fire.epub"
  harry_potter_05:
    label: HP5
    epub: "J.K. Rowling - Harry Potter 05 - Order of the Phoenix.epub"
  harry_potter_07:
    label: HP7
    epub: "J.K. Rowling - Harry Potter 07 - Deathly Hallows.epub"
  harry_potter_08:
    label: HP8
    epub: "J.K. Rowling - Harry Potter 08 - Cursed Child.epub"
  hunger_games:
    label: HungerGames
    epub: "Suzanne Collins - The Hunger Games.epub"
  i_know_why_the_caged_bird_sings:
    label: CagedBird
    epub: "Maya Angelou - I Know Why the Caged Bird Sings.epub"
  in_cold_blood:
    label: InColdBlood
    epub: "Truman Capote - In Cold Blood.epub"
  invisible_man:
    label: InvisibleMan
    epub: "Ralph Ellison - Invisible Man.epub"
  i_robot:
    label: IRobot
    epub: "Isaac Asimov - I, Robot.epub"
  iron_heel:
    label: IronHeel
    epub: "Jack London - The Iron Heel.epub"
  it:
    label: It
    epub: "Stephen King - It.epub"
  lilith_s_brood:
    label: LilithBrood
    epub: "Octavia Butler - Lilith's Brood.epub"
  little_life:
    label: LittleLife
    epub: "Hanya Yanagihara - A Little Life.epub"
  lord_of_the_flies:
    label: LordFlies
    epub: "William Golding - Lord of the Flies.epub"
  man_in_the_high_castle:
    label: HighCastle
    epub: "Philip K. Dick - The Man in the High Castle.epub"
  martian:
    label: Martian
    epub: "Andy Weir - The Martian.epub"
  men_without_women:
    label: MenWoWomen
    epub: "Ernest Hemingway - Men Without Women.epub"
  moby_dick:
    label: MobyDick
    epub: "Herman Melville - Moby-Dick.epub"
  nineteen_eighty_four:
    label: 1984
    epub: "George Orwell - Nineteen Eighty-Four.epub"
  of_mice_and_men:
    label: MiceAndMen
    epub: "John Steinbeck - Of Mice and Men.epub"
  old_man_and_the_sea:
    label: OldManSea
    epub: "Ernest Hemingway - The Old Man and the Sea.epub"
  old_mans_war:
    label: OldMansWar
    epub: "John Scalzi - Old Man's War.epub"
  one_flew_over_the_cuckoos_nest:
    label: CuckoosNest
    epub: "Ken Kesey - One Flew Over the Cuckoo's Nest.epub"
  on_the_road:
    label: OnTheRoad
    epub: "Jack Kerouac - On the Road.epub"
  prelude_to_foundation:
    label: PreludeFnd
    epub: "Isaac Asimov - Prelude to Foundation.epub"
  road:
    label: Road
    epub: "Cormac McCarthy - The Road.epub"
  salems_lot:
    label: SalemsLot
    epub: "Stephen King - Salem's Lot.epub"
  scarlet_letter:
    label: ScarletLtr
    epub: "Nathaniel Hawthorne - The Scarlet Letter.epub"
  shining:
    label: Shining
    epub: "Stephen King - The Shining.epub"
  silence_of_the_lambs:
    label: SilncLambs
    epub: "Thomas Harris - The Silence of the Lambs.epub"
  slaughterhouse_five:
    label: Slaught5
    epub: "Kurt Vonnegut - Slaughterhouse-Five.epub"
  snow_crash:
    label: SnowCrash
    epub: "Neal Stephenson - Snow Crash.epub"
  stand:
    label: Stand
    epub: "Stephen King - The Stand.epub"
  their_eyes_were_watching_god:
    label: EyesWtchGd
    epub: "Zora Neale Hurston - Their Eyes Were Watching God.epub"
  to_kill_a_mockingbird:
    label: Mockingbird
    epub: "Harper Lee - To Kill a Mockingbird.epub"
  tree_grows_in_brooklyn:
    label: TreeBklyn
    epub: "Betty Smith - A Tree Grows in Brooklyn.epub"
  ubik:
    label: Ubik
    epub: "Philip K. Dick - Ubik.epub"
  visit_from_the_goon_squad:
    label: GoonSquad
    epub: "Jennifer Egan - A Visit from the Goon Squad.epub"
